config/routes.rb
Friendlymail::Application.routes.draw do
  
    match '/logout', :to=> "sessions#destroy", :as=> "logout"
	match '/login', :to=> "sessions#new", :as=> "login"
	match '/register', :to=> "users#create", :as=> "register"
	match '/signup', :to=> "users#new", :as=> "signup"
  
	resources :users
  	resource :session
	#resources :messages
	resources :messages do
		put 'complete', :on => :collection
	end
	match "/messages/destroy/:id", :to => "messages#destroy", :as =>"destroy_message"
	root :to => 'home#index'
	
end

app/models/message.rb
class Message < ActiveRecord::Base

belongs_to :user

validates :recipient,      :presence   => true,
                           :length     => { :within => 1..100 },
                           :format     => { :with => Authentication.email_regex, :message => Authentication.bad_email_message }
validates :subject,        :presence   => true,
                           :length     => { :within => 1..100 }
validates :text,           :length     => { :within => 1..5000 }   
      
	def initialize(keys={})
		super
		self.status ||= "new"
	end
                                                                     
	def self.search(search, user_id)
	  if search
		find(:all, :conditions => ["lower(subject) LIKE ? AND user_id = ?", "%#{search.downcase}%", user_id.to_s], :order => "created_at ASC")
	  else
		find(:all, :conditions => ["user_id = ?", user_id.to_s], :order => "created_at ASC")
	  end
	end

	def self.by_status(status, user_id)
		find(:all, :conditions => ["status = ? AND user_id = ?", status, user_id.to_s], :order => "created_at ASC")
	end
	
	def self.count_search(user_id)
		count(:all, :conditions => ["user_id = ?", user_id.to_s])
	end

	def self.count_by_status(status, user_id)
		count(:all, :conditions => ["status = ? AND user_id = ?", status, user_id.to_s])
	end
end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken

  set_table_name 'users'

  validates :login, :presence   => true,
                    :uniqueness => true,
                    :length     => { :within => 3..40 },
                    :format     => { :with => Authentication.login_regex, :message => Authentication.bad_login_message }

  validates :name,  :format     => { :with => Authentication.name_regex, :message => Authentication.bad_name_message },
                    :length     => { :maximum => 100 },
                    :allow_nil  => true

  validates :email, :presence   => true,
                    :uniqueness => true,
                    :format     => { :with => Authentication.email_regex, :message => Authentication.bad_email_message },
                    :length     => { :within => 6..100 }

  
  has_many :messages, :dependent => :destroy
  # HACK HACK HACK -- how to do attr_accessible from here?
  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  attr_accessible :login, :email, :name, :password, :password_confirmation



  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.  
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(login, password)
    return nil if login.blank? || password.blank?
    u = find_by_login(login.downcase) # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end

  def email=(value)
    write_attribute :email, (value ? value.downcase : nil)
  end

  protected
    


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.xml
  def index
  	@new_messages_size = Message.count_by_status('new', current_user.id)
  	@marked_messages_size = Message.count_by_status('marked', current_user.id)
  	@trash_messages_size = Message.count_by_status('trash', current_user.id)
  	@messages_size = Message.count_search(current_user.id)
	m_page = params[:m_page].to_i
	@m_id = params[:m_id]
	case params[:m_status]
	when 'new'
		@messages = Message.by_status('new', current_user.id)
	when 'marked'
		@messages = Message.by_status('marked', current_user.id)
	when 'trash'
		@messages = Message.by_status('trash', current_user.id)
	else
		@messages = Message.search(params[:search], current_user.id)
	end
	m_size = @messages.size
	if m_size%MESSAGE_ON_PAGE==0
		@number_of_pages = m_size/MESSAGE_ON_PAGE
	else
		@number_of_pages = m_size/MESSAGE_ON_PAGE+1
	end
	m_page=1 if m_page < 1
	m_page=@number_of_pages if (m_page>@number_of_pages && @number_of_pages>0)
	#@m_page=m_page
	@messages = @messages[((m_page-1)*MESSAGE_ON_PAGE)..(((m_page-1)*MESSAGE_ON_PAGE)+MESSAGE_ON_PAGE-1)]
	@m_id = params[:m_id]
	unless @m_id.nil?
		@message = Message.find(@m_id)
	end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
  	
    @message = Message.find(params[:id])
    if current_user.id == @message.user_id

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
    else
    respond_to do |format|
      format.html { redirect_to('/messages') }
      format.xml  { head :ok }
    end
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
  
    @message = Message.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
    unless current_user.id == @message.user_id
    respond_to do |format|
      format.html { redirect_to('/messages') }
      format.xml  { head :ok }
    end
    end

  end

  # POST /messages
  # POST /messages.xml
  def create
  	#Message {"pecipient"=>"sdfds", "subject"=>"sdfsdf", "text"=>"fds fsd", "status"=>"uhk" was successfully created.

    @message = Message.new(params[:message])
	@message['user_id'] = current_user.id

    respond_to do |format|
      if @message.save
        flash[:notice] = "Message was successfully created."
        format.html { redirect_to(@message) }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end

  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        flash[:notice] = 'Message was successfully updated.'
        format.html { redirect_to(@message) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
  	
    @message = Message.find(params[:id])
    @message.destroy if current_user.id == @message.user_id

    respond_to do |format|
      format.html { redirect_to(messages_url) }
      format.xml  { head :ok }
    end
  end

  def complete
#Защита от смены статуса (изменения/удаления) чужих сообщений
	message_ids = []
	params[:message_ids] ||= []
	params[:message_ids].each{|m_id|
	if current_user.id == Message.find(m_id).user_id
		message_ids.push(m_id)
	end
	}
#----
  	if params[:commit]=='Marked as Important'
		Message.update_all(["status=?", 'marked'], :id => message_ids)
  	elsif params[:commit]=='Unmarked as Important'
		Message.update_all(["status=?", 'new'], :id => message_ids)
	elsif params[:commit]=='Move to Trash/Delete'
		Message.where(:status => 'trash').delete_all(:id => message_ids)
		Message.where(:status => 'new').update_all(["status=?", 'trash'], :id => message_ids)
		Message.where(:status => 'marked').update_all(["status=?", 'trash'], :id => message_ids)
	end

  	redirect_to :back, :params => @params
  end
end

app/views/messages/_form.html.erb
<% form_for(@message) do |message_form| %>
<%= errors_for(@message, "Unable to add new message").html_safe %>

<div class="message_form">
<% unless @message.nil? %>
 <% form_for(@message) do |message_form| %>
<table id="table"  width="80%" align="center" style="background-color:silver" cellpadding="2" cellspacing="0" border="1">
<tr>
<td width="20%">Recipient</td><td width="40%"><%= message_form.text_field :recipient %></td>
<td>
<% @message.errors['recipient'].each do |error| %>
<%=error%><br />
<% end %>
</td>
</tr><tr>
<td>Subject</td><td><%= message_form.text_field :subject %></td>
<td>
<% @message.errors['subject'].each do |error| %>
<%=error%><br />
<% end %>
</td>
</tr><tr>
<td>Text</td><td><%= message_form.text_area :text %></td>
<td>
<% @message.errors['text'].each do |error| %>
<%=error%><br />
<% end %>
</td>
</tr><tr>
<td>Status</td><td><%= @message['status'] %></td>
<td>
<% @message.errors['status'].each do |error| %>
<%=error%><br />
<% end %>
</td>
</tr>
</table>
 <% end %>
<% end %>
</div>
<p><center><%= message_form.submit "Save" %></center></p>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render :partial => "form" %>
<center>
<%= link_to 'Back', messages_path %> |
<%= link_to 'Show', @message %> |
<%= link_to 'Destroy', @message, :confirm => 'Are you sure?', :method => :delete, :remote=>true %>
</center>

app/views/messages/index.html.erb
<table id="form_messages"  width="80%" align="center" cellpadding="2" cellspacing="0" border="1">
<tr><td width="20%" style="padding-left: 10; background-color: silver;">
<%= button_to 'New message', new_message_path, :method => 'get' %>
<% form_tag messages_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search by subject", :name => nil %>
  </p>
<% end %>
<%= link_to "all messages", messages_path(:m_status=>'all')  %> <%=@messages_size%><br />
<hr>
<%= link_to "new messages", messages_path(:m_status=>'new')  %> <%=@new_messages_size%><br />
<%= link_to "marked messages", messages_path(:m_status=>'marked')  %> <%=@marked_messages_size%><br />
<%= link_to "trash messages", messages_path(:m_status=>'trash')  %> <%=@trash_messages_size%><br />
</td><td width="60%" style="padding-left: 10; background-color: silver;">
<% if @message.nil? %>

<%form_tag complete_messages_path, :method => :put do %>
<%= submit_tag "Marked as Important" %> <%= submit_tag "Unmarked as Important" %> <%= submit_tag "Move to Trash/Delete" %>
<table id="table"  width="100%" align="center" style="background-color:silver" cellpadding="2" cellspacing="0" border="1">
<tr>
<td>&nbsp;</td><td>&nbsp;</td><td width="20%">Recipient</td><td>Subject</td><td>Text</td></tr>
<% @messages.each_with_index do |message, index| %>
<tr>
<td><label for="message_ids_"><%= check_box_tag "message_ids[]", message.id %></label></td>
<td><%if message.status=='marked' %>
i
<%elsif message.status=='trash' %>
t
<% else %>
&nbsp;
<% end %>
</td>
<td>
    <%= link_to "#{message.recipient}", messages_path(:m_id=>message.id)  %>
</td><td>
    <%= link_to "#{message.subject}", messages_path(:m_id=>message.id)  %>
</td><td>
    <%= link_to "#{message.text[0..40]}", messages_path(:m_id=>message.id)  %>
</td>
</tr>
<% end %>
</table>

<div id="pages" align="right">
<% for i in 1..@number_of_pages %>
<%= link_to i, messages_path(:m_status=>params[:m_status], :m_page=>i)  %>&nbsp;
<% end %>
</div>
<%end%>

<%else%>
<% form_for(@message) do |message_form| %>
<table id="table"  width="100%" align="center" style="background-color:silver" cellpadding="2" cellspacing="0" border="1">
<tr>
<td width="20%">Recipient</td><td><%= h @message.recipient %>&nbsp;</td>
</tr><tr>
<td>Subject</td><td><%= h @message.subject %>&nbsp;</td>
</tr><tr>
<td>Text</td><td><%= raw @message.text.gsub(/\n/, '<br/>') %>&nbsp;</td>
</tr><tr>
<td>Status</td><td><%= h @message.status %>&nbsp;</td>
</tr>
</table>
    <%= link_to 'Show', @message %>
    <%= link_to 'Edit', edit_message_path(@message) %>
    <%= link_to 'Destroy',destroy_message_path(:id=>@message.id), :confirm => 'Are you sure?' %>
 <% end %>
<% end %>
</tr>
</table>

app/views/messages/new.html.erb
<h1>New message</h1>
<%= render :partial => "form" %>

<center><%= button_to 'Back', messages_path, :method=>'get'%></center>

app/views/messages/show.html.erb
<h1>Show message</h1>
<table id="table"  width="80%" align="center" style="background-color:silver" cellpadding="2" cellspacing="0" border="1">
<tr>
<td width="20%">Recipient</td><td><%= h @message.recipient %>&nbsp;</td>
</tr><tr>
<td>Subject</td><td><%=h @message.subject %>&nbsp;</td>
</tr><tr>
<td>Text</td><td><%= raw @message.text.gsub(/\n/, '<br/>') %>&nbsp;</td>
</tr><tr>
<td>Status</td><td><%= h @message.status  %>&nbsp;</td>
</tr>
</table>

<center>

<%= link_to 'Back', messages_path %> |
<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Destroy', @message, :confirm => 'Are you sure?', :method => :delete, :remote=>true %>
</center>