config/routes.rb
Friendlymail::Application.routes.draw do
  
    match '/logout', :to=> "sessions#destroy", :as=> "logout"
	match '/login', :to=> "sessions#new", :as=> "login"
	match '/register', :to=> "users#create", :as=> "register"
	match '/signup', :to=> "users#new", :as=> "signup"
  
	resources :users
  	resource :session
	#resources :messages
	resources :messages do
		put 'complete', :on => :collection
	end
	match "/messages/destroy/:id", :to => "messages#destroy", :as =>"destroy_message"
	root :to => 'home#index'
	
end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken

  set_table_name 'users'

  validates :login, :presence   => true,
                    :uniqueness => true,
                    :length     => { :within => 3..40 },
                    :format     => { :with => Authentication.login_regex, :message => Authentication.bad_login_message }

  validates :name,  :format     => { :with => Authentication.name_regex, :message => Authentication.bad_name_message },
                    :length     => { :maximum => 100 },
                    :allow_nil  => true

  validates :email, :presence   => true,
                    :uniqueness => true,
                    :format     => { :with => Authentication.email_regex, :message => Authentication.bad_email_message },
                    :length     => { :within => 6..100 }

  
  has_many :messages, :dependent => :destroy
  # HACK HACK HACK -- how to do attr_accessible from here?
  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  attr_accessible :login, :email, :name, :password, :password_confirmation



  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.  
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(login, password)
    return nil if login.blank? || password.blank?
    u = find_by_login(login.downcase) # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end

  def email=(value)
    write_attribute :email, (value ? value.downcase : nil)
  end

  protected
    


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Be sure to include AuthenticationSystem in Application Controller instead
#  include AuthenticatedSystem
  

  # render new.rhtml
  def new
    @user = User.new
  end
 
  def create
    logout_keeping_session!
    @user = User.new(params[:user])
    #success = @user && @user.save
  #  if verify_recaptcha
    	success =  @user && @user.save
    	if success && @user.errors.empty?
    	
    		#	UserMailer.deliver_registration_confirmation(@user)
    		
    		
            # Protects against session fixation attacks, causes request forgery
		  # protection if visitor resubmits an earlier form using back
		  # button. Uncomment if you understand the tradeoffs.
		  # reset session
		  self.current_user = @user # !! now logged in
		  redirect_back_or_default('/', :notice => "Thanks for signing up!  We're sending you an email with your activation code.")
		else
		  flash.now[:error]  = "We couldn't set up that account, sorry.  Please try again."
		  render :action => 'new'
		end
	#else
#		flash[:error] = "The words do not match the ones in the recaptcha image!"
#		render :action => 'new'
#	end
  end

end

app/views/users/_user_bar.html.erb
<% if logged_in? -%>
  <div id="user-bar-greeting">Logged in as <%= link_to_current_user :content_method => :login %></div>
  <div id="user-bar-action"  >(<%= link_to "Log out", logout_path, { :title => "Log out" }    %>)</div>
<% else -%>
  <div id="user-bar-greeting"><%= link_to_login_with_IP 'Not logged in', :style => 'border: none;' %></div>
  <div id="user-bar-action"  ><%= link_to "Log in",  login_path,  { :title => "Log in" } %> /
                               <%= link_to "Sign up", signup_path, { :title => "Create an account" } %></div>
<% end -%>

app/views/users/new.html.erb
<h1>Sign up as a new user</h1>
<% @user.password = @user.password_confirmation = nil %>

<%= error_messages_for :user %>
<% form_for :user, :url => users_path do |f| -%>
<p><%= f.label :login %><br/>
<%= f.text_field :login %></p>

<p><%= f.label :email %><br/>
<%= f.text_field :email %></p>

<p><%= f.label :password %><br/>
<%= f.password_field :password %></p>

<p><%= f.label :password_confirmation, 'Confirm Password' %><br/>
<%= f.password_field :password_confirmation %></p>

<p><%= submit_tag 'Sign up' %></p>
<% end -%>
<p><%= button_to "Back", root_path  %></p>